### ISSUE TITLE
Radix 36 is broken?

### ISSUE THREAD

**Issue by dvdplm** [jjpe/radix#1]
Hi,
I tried to use this code to convert to base36 and ran into a panic with this:

```rust
RadixNum::from(15123093122 as u64).with_radix(36);
// Error `IllegalDigit(32)`
```
Can you help me understand what is going on?

**Comment by jjpe** [comment]
Hi!

The check for base 32 and up was a bit buggy, so base32 and up doesn't work atm.
I'll push a new release shortly that goes up all the way to (and includes) base 36, but before I do, would you be willing test the commit with hash `ed1ae7eb988e2a4b53631f0d66a26db58f25f788`?
It works over here, so if it does for you as well I'll tag and release it.

You can test with the hash by changing the line that looks like
````
radix = "0.3"
````
 to 
````
radix = { git = "https://github.com/jjpe/radix.git", rev = "ed1ae7e" }
````
in your Cargo.toml.

**Comment by jjpe** [comment]
I've pushed out `0.3.4` so I'm closing this issue.
